## Dated: Friday, 4th of September, 2026
Signed in: 5:00

Signed out: 6:20

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.3.5


In [5]:
sample=[1,2,3,4,5]
#sample *=2 If I left this, in the next block, the numbers in samplearray would be repeated 2wice because the sample itself was repeated.
print(sample)

[1, 2, 3, 4, 5]


In [6]:
samplearray=np.array(sample)
samplearray*=2
print(type(samplearray))
print(samplearray)
print(samplearray.ndim)
t=np.array(78)
print(t.ndim)

<class 'numpy.ndarray'>
[ 2  4  6  8 10]
1
0


Multidimensional Lists

In [7]:
alpha = np.array([["a","b","c", "d", "e"], ["a","b","c", "d","e"]])
print(alpha)
print(alpha.ndim)
print(alpha.shape)
print()

trad= [["a","b","c"],
       ["d", "e", "f","g","h"]]
print(trad)
print(type(trad))
print(trad[0][2]+trad[1][0]+trad[0][2])
print()

tradarray= np.array([["a","b","c","",""],
       ["d", "e", "f","g","h"]])
print(tradarray)
print(tradarray.shape)
print()

alphabers = np.array([[[["a","b","c","d","e"], ["f","g","h","i","j"]], 
                      [["k","l","m", "n", "o"], ["p","q","r", "s","t"]],
                      [["u","v","w","x","y"], ["z","","","",""]],
                    [["1","2","3","4","5"], ["6","7","8","9","0"]]]])
print(alphabers.ndim)
print(alphabers.shape)
print()

single=np.array(8)
print(single.shape)
print(single.ndim)

[['a' 'b' 'c' 'd' 'e']
 ['a' 'b' 'c' 'd' 'e']]
2
(2, 5)

[['a', 'b', 'c'], ['d', 'e', 'f', 'g', 'h']]
<class 'list'>
cdc

[['a' 'b' 'c' '' '']
 ['d' 'e' 'f' 'g' 'h']]
(2, 5)

4
(1, 4, 2, 5)

()
0


## Dated: Sat. 5th of Sept, 2026
Signed in --- 7:40

Didn't do much, (like nothing)

## Dated: Thursday, 10th of Sept, 2026

Signed in 6:20


In [8]:
ass=np.array(78)
print (ass)

78


In [9]:
print("Mark: So, how many asses have you had?")
print(f"Well, {alphabers[0,3,1,4].capitalize()} {alphabers[0,0,0,0].capitalize()}{alphabers[0,1,1,3].capitalize()}{alphabers[0,1,1,3].capitalize()}")

Mark: So, how many asses have you had?
Well, 0 ASS


Signed out--- 7:05

## Dated: Wedn. 23rd of Sept, 2026
Signed in 19:15

### Splicing

In [10]:
ay=np.array([[1,2,3,4], 
             [5,6,7,8], 
             [9,10,11,12], 
             [13,14,15,16]])
print(ay.ndim)
print(ay.shape)

2
(4, 4)


Splicing for rows

In [11]:
print(f"One row only: {ay[3]}")
print()
print("For multiple rows") 
print(f"1. {ay[0:3]}")
print()
print("2. Reverse technique, the rows in reverse:") 
print(ay[::-1])


One row only: [13 14 15 16]

For multiple rows
1. [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2. Reverse technique, the rows in reverse:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Splicing for columns

In [12]:
print("One column only")
print()

print(f"1. Full last column: {ay[:, 3]}")
print(f"2. Last column but from the 1st index: {ay[1:, 3]}")
print(f"3. Reverse technique, last column: {ay[:, -1]}")
print(f"4. Reverse technique, 2nd to last column: {ay[:, -2]}")
print()

print("For multiple columns:")
print()

print("1. Full first 3 columns:")
print(ay[:, 0:3])
print()

print("2. First 3 columns, ends on the 3rd row:")
print(ay[0:3, 0:3])
print()

print("3. Full columns, begins from the 3rd row:")
print(ay[2:, 0:4])
print()

print("4. Full columns, begins from the 3rd row and the 2nd column:")
print(ay[2:, 1:4])
print()

print("5. Begins from the 2nd row to the 3rd row, 3rd column to the 4th column:")
print(ay[1:3, 2:4])
print()


One column only

1. Full last column: [ 4  8 12 16]
2. Last column but from the 1st index: [ 8 12 16]
3. Reverse technique, last column: [ 4  8 12 16]
4. Reverse technique, 2nd to last column: [ 3  7 11 15]

For multiple columns:

1. Full first 3 columns:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

2. First 3 columns, ends on the 3rd row:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

3. Full columns, begins from the 3rd row:
[[ 9 10 11 12]
 [13 14 15 16]]

4. Full columns, begins from the 3rd row and the 2nd column:
[[10 11 12]
 [14 15 16]]

5. Begins from the 2nd row to the 3rd row, 3rd column to the 4th column:
[[ 7  8]
 [11 12]]



Splicing adding steps

In [13]:
print("Begins from the very first row, first column, but in steps of 2")
print(ay[:, ::2])
print()

print("Begins from the very first row, 2nd column, through to the end of the data set, in steps of 2 ")
print(ay[:, 1::2])
print()

print("Begins from the 2nd row, first column, but in single reverse steps i.e -1")
print(ay[1:, : :-1])
print()

print("Begins from the 2nd row to the 3rd row, first column, but in double reverse steps i.e -2")
print(ay[1:3, : :-2])
print()

Begins from the very first row, first column, but in steps of 2
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

Begins from the very first row, 2nd column, through to the end of the data set, in steps of 2 
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]

Begins from the 2nd row, first column, but in single reverse steps i.e -1
[[ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

Begins from the 2nd row to the 3rd row, first column, but in double reverse steps i.e -2
[[ 8  6]
 [12 10]]



In [14]:
print("A matrix of the first 2 rows and the first 2 columns")
print(ay[:2, :2])
print()

print("A matrix of the first 2 rows and the last 2 columns")
print(ay[0:2, 2:4])
print()

print("A matrix of the last 2 rows and the first 2 columns")
print(ay[2:, :2])
print()

print("A matrix of the last 2 rows and the last 2 columns")
print(ay[2:, 2:])
print()

A matrix of the first 2 rows and the first 2 columns
[[1 2]
 [5 6]]

A matrix of the first 2 rows and the last 2 columns
[[3 4]
 [7 8]]

A matrix of the last 2 rows and the first 2 columns
[[ 9 10]
 [13 14]]

A matrix of the last 2 rows and the last 2 columns
[[11 12]
 [15 16]]



Signed out --- 21:45

## Dated: Monday, 29th of Sept. 2026

Signed in --- 16:40

### Scalar Arithemetic

In [17]:
ari = np.array([2, 4, 8])
print(ari+1)
print(ari-2)
print(ari*3)
print(ari/4)
print(ari**5)

[3 5 9]
[0 2 6]
[ 6 12 24]
[0.5 1.  2. ]
[   32  1024 32768]


### Vectorized Math Functions